### ISSUE TITLE
Alarm.com integration not loading

### ISSUE THREAD

**Issue by mikesalz** [Xorso/pyalarmdotcom#14]
Alarm.com is not loading, and generating this error.  This has been happening all day, even after a restart.
```

Error while setting up alarmdotcom platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyalarmdotcom/pyalarmdotcom.py", line 188, in async_login
    self.state = tree.select(self.ALARM_STATE)[0].get_text()
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/src/homeassistant/homeassistant/components/alarmdotcom/alarm_control_panel.py", line 48, in async_setup_platform
    await alarmdotcom.async_login()
  File "/usr/src/homeassistant/homeassistant/components/alarmdotcom/alarm_control_panel.py", line 70, in async_login
    await self._alarm.async_login()
  File "/usr/local/lib/python3.7/site-packages/pyalarmdotcom/pyalarmdotcom.py", line 197, in async_login
    '#{}'.format(self.ERROR_CONTROL))[0].attrs.get('value')
IndexError: list index out of range
```

**Comment by jfette** [comment]
The PDA workflow doesn't seem to be working anymore.  No matter the user agent I attempt, it's still redirecting to the standard alarm.com login page.

```
$ curl -A "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1" -kv https://www.alarm.com/pda/
*   Trying 192.155.71.71...
* TCP_NODELAY set
* Connected to www.alarm.com (192.155.71.71) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=VA; L=Mc Lean; O=Alarm.com Incorporated; OU=Cloud; CN=*.alarm.com
*  start date: Mar 12 00:00:00 2019 GMT
*  expire date: Mar 16 12:00:00 2021 GMT
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /pda/ HTTP/1.1
> Host: www.alarm.com
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Cache-Control: private
< Location: https://www.alarm.com:443/login.aspx
< Server: Microsoft-IIS/10.0
< Set-Cookie: ASP.NET_SessionId=d5g2wyadpqj0uw1i14r5wnu5; path=/; secure; HttpOnly; SameSite=Lax
< X-AspNet-Version: 4.0.30319
< X-Powered-By: ASP.NET
< P3P: policyref="/w3c/p3p.xml",CP="OUR SAMa ADM UNI BUS ALL CUR DSP TAI COR IND STA"
< Access-Control-Allow-Origin: *
< Date: Tue, 17 Mar 2020 02:02:01 GMT
< Content-Length: 0
< Set-Cookie: BIGipServer~AlarmApplication~Alarm_WEBADC_Alarm_HTTPS=!XGLS2ivKmAZE35Xfq1PpycjqXg8oNa0KWZa6nmx0vGeNItddsPczgMkqM9sFWYLmArLr4GuvFlmFrUI=; path=/; Httponly; Secure
<
* Connection #0 to host www.alarm.com left intact
* Closing connection 0
```
Edit: Updated with correct user agent from the script.
