### ISSUE TITLE
ghostdriver.log causing fail to load

### ISSUE THREAD

**Issue by thebloodynine** [Xorso/pyalarmdotcom#4]
Been hitting this issue, very new to python and hass.  I think it might be due to selenium setting the log_path if none is specified to a file vs. a dir path, thus the Permission Denied error code.  Tried to edit selenium's service.py to test this, but the changes revert on a restart.  Maybe you can help?

`16-07-01 05:32:56 homeassistant.components.alarm_control_panel: Error while setting up platform alarmdotcom
Traceback (most recent call last):
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 98, in _setup_platform
    discovery_info)
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/alarm_control_panel/alarmdotcom.py", line 36, in setup_platform
    password)])
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/alarm_control_panel/alarmdotcom.py", line 47, in __init__
    self._alarm = Alarmdotcom(username, password, timeout=10)
  File "/home/hass/.homeassistant/deps/pyalarmdotcom/pyalarmdotcom.py", line 82, in __init__
    if not self._login():
  File "/home/hass/.homeassistant/deps/pyalarmdotcom/pyalarmdotcom.py", line 95, in _login
    self._driver = webdriver.PhantomJS()
  File "/home/hass/.homeassistant/deps/selenium/webdriver/phantomjs/webdriver.py", line 51, in __init__
    log_path=service_log_path)
  File "/home/hass/.homeassistant/deps/selenium/webdriver/phantomjs/service.py", line 50, in __init__
    service.Service.__init__(self, executable_path, port=port, log_file=open(log_path, 'w'))
PermissionError: [Errno 13] Permission denied: 'ghostdriver.log'`

Suspect line from selenium's service.py (/home/hass/.homeassistant/deps/selenium/webdriver/phantomjs/service.py)

`if not log_path:
            log_path = "ghostdriver.log"
`

**Comment by bgianfo** [comment]
I'm seeing this as well.

**Comment by jordandrako** [comment]
I'm seeing this too. 
Maybe changing line 95 on pyalarmdotcom.py to 
`        self._driver = webdriver.PhantomJS(service_log_path='/tmp/ghostdriver.log')`
or, as a different branch the AiO installer could use as a dependency:
`        self._driver = webdriver.PhantomJS(service_log_path='/srv/hass/hass_venv/ghostdriver.log')`

I have tried this but every time I restart the hass service, it overwrites it back to normal, so I can't test it.

**Comment by lorddaren** [comment]
These should be fixed with the PR that I have open with home-assistant. I have removed the dependency in working with phantomjs and selenium.
